### ISSUE TITLE
Under what breaktipe do Villagers fall?

### ISSUE THREAD

**Issue by iNko97** [DevotedMC/CropControl#6]
Villagers can break and plant crops since 1.8, and I was wondering, under what breaktipe do they get listed?
I assumed natural, but was not quite sure (Not that I need it, just a personal curiosity :P)

**Comment by xFier** [comment]
Villages placing crops won't be tracked. As far as the plugin is concerned it's a pre-existing crop and thus not important. However breaks are* be handled under natural.

**Comment by iNko97** [comment]
I was talking about villagers, not villages, let's say someone makes a farm using a villager design such as this one https://www.youtube.com/watch?v=VB1n_2bLk4o . 
How would cropcontrol register newly placed carrots by villagers (Probably would ignore them?) and how would it react to a villager breaking a player's placed carrot?

**Comment by xFier** [comment]
Forgive the typo. Villagers placing carrots will not be registered. The
plugin only tracks blocks/plants placed specifically by the player as means
of ensuring they actually are harvesting these crops and trees themselves.
Rather than breaking naturally generated ones.

As a result these crops will not be tracked by the plugin and therefore
will not be possible to drop custom drops.

However for crops placed by the player, which are broken by a villager will
be covered under the natural break type. (Via the entity change block event)

**Comment by iNko97** [comment]
Thanks for solving my curiosity!
